version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_api
    restart: unless-stopped
    env_file: .env
    environment:
      # Inside Docker network, use service names instead of localhost
      DATABASE_URL: postgresql+psycopg2://rag_user:rag_pass@postgres:5432/ragdb
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_COLLECTION: research_papers
      # Talk to Ollama running on the HOST machine
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    depends_on:
      - postgres
      - qdrant
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:16
    container_name: rag_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_pass
    ports:
      - "5433:5432"  # host:container (use 5433 on host to avoid conflicts)
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  pgdata:
  qdrant_storage:

